### PR TITLE
Final

### LINKED ISSUE #41: handle style from main branch
as discussed in our meeting today 
we have to make Yousra's style match/mergeable with main branch

### PR DESCRIPTION
**Pull request by YousraElmag**
I add function to change the background color to correct answers to green or red if it's false ,and add settimeout 3 sec to go to next quetion

### CODE REVIEW

**Comment by YousraElmag** [comment]
handleAnswerClick function called two time that's make the score increase 2 every correct answer I fixed

**Review by M-Hajjar — APPROVED** [review]
looks great to me 
we had a bug but now its fixed with updating answeView.js

and on the welcome page I added a 4. rule in index.html says " You can only make 3 mistakes "

**Comment by azizsigar** [comment]
Screenshot 2024-06-01 at 09 25 41


i added question index, we can see our score and question index same time

**Review by azizsigar — APPROVED** [review]

**Comment by azizsigar** [comment]
i added local storage but score not storing. progress storing. question index not working now.

**Review by beimnet11 — APPROVED** [review]

**Review by beimnet11 — APPROVED** [review]

**Review by beimnet11 — APPROVED** [review]

**Review by azizsigar — APPROVED** [review]
Its final version of project! No more commit a.u.b

**Review by M-Hajjar — CHANGES_REQUESTED** [review]
do not merge this PR 
we have already merged it through PR " working #43 "

**Comment by M-Hajjar** [comment]
we have already merged it through PR " working https://github.com/imtiaz101325/hyf-c48-w2-browsers-quiz-app-coffee-break/pull/43 "

**Pull request closed without merging**
