### PR TITLE
add  js files

### LINKED ISSUE #29: making a simple Design with buttons
here we need to add yousra s work with aziz function

### PR DESCRIPTION
**Pull request by YousraElmag**

### CODE REVIEW

**Review by M-Hajjar — COMMENTED** [review]
this is nice 
im gonna try to improve it

**Review by azizsigar — COMMENTED** [review]
LGFM but i think we repeated the codes.

**Review by beimnet11 — COMMENTED** [review]
looks good,

**Review by M-Hajjar — APPROVED** [review]
i think it's great as a Design
it only can be improve if we wanna keep saving the score after refreshing

but I think we can merge it to main and continue from there

**Review by azizsigar — APPROVED** [review]
LGTM

**Review by beimnet11 — APPROVED** [review]
looks good to me

**Pull request merged**
