### PR TITLE
fixed restart

### LINKED ISSUE #38: Buge :  a user see a blank page after restart the quiz
when a user finishes the quiz and clicks " go home " to restart the quiz 
a blank page shows up 
Screenshot (22)
as Imtiaz explained to me it has something to do in qustionPage.js 
the function needs to know where to go next after its been clicked  
d5be65ce-4784-4618-be4a-58e9cfa52935

### PR DESCRIPTION
**Pull request by azizsigar**
1- i fixed the `repeating` codes. ending page 2 diffirent btn is doing same restart feature.
i **removed** the try again btn cause it was doing same job with try again.
2-when play again the quiz the questions was not loading. now its **working** well. 

need to improve!
some `namings` are not **_camelCase_** in `questionpage`.js
some const are storing in questionpage.js its need to be in `Consts.js file`

### CODE REVIEW

**Comment by azizsigar** [comment]
fixed lovelyprettier
able to merge

**Review by M-Hajjar — APPROVED** [review]
looks good to me 
thanks for fixing this

**Review by M-Hajjar — CHANGES_REQUESTED** [review]
we still have a problem here thou 
as i understand the score now saves the correct answers 
even after refreshing the page 
but it saves it for ever ( even after the quiz is done )
Screenshot (23)

**Comment by azizsigar** [comment]
when restart again score was not restarting. score is continue the counting. now when we click start its r`esetting the score `points.

**Review by M-Hajjar — APPROVED** [review]
perfect

**Pull request merged**
