### PR TITLE
Change npm project name to "coffee-break-quiz-app"

### LINKED ISSUE #1: In `package.json` the `name` field should be the name of the project
In the projects `package.json` the `name` filed comes from the original boilerplate. We need to change it to something meaningful.

### PR DESCRIPTION
**Pull request by imtiaz101325**
This pull request includes a single commit that changes the name of the npm project from "js-quiz-starter" to "coffee-break-quiz-app".

closes #1

### CODE REVIEW

**Review by azizsigar — CHANGES_REQUESTED** [review]
i like it

**Review by M-Hajjar — COMMENTED** [review]
yeah sounds good

**Review by M-Hajjar — APPROVED** [review]
yeah sounds good

**Comment by YousraElmag** [comment]
look good

**Pull request merged**
